### ISSUE TITLE
Can you also sharing the assets to generate hybrid ray tracing output?

### ISSUE THREAD

**Issue by horusli** [diharaw/HybridRendering#1]
thanks for sharing hybrid ray tracing rendering work combining rasterization and ray tracing together. 
can you also please share the assets accompany to generate the rendering result?

**Comment by diharaw** [comment]
Sure thing, I'll add a prebuilt release with the assets soon.

**Comment by horusli** [comment]
> Sure thing, I'll add a prebuilt release with the assets soon.

hi, any chance that you can provide the sponza scene asset?
I try one copy from another repo yet it seems does not working, the program crashed when draw gbuffer.

**Comment by diharaw** [comment]
> > Sure thing, I'll add a prebuilt release with the assets soon.
> 
> hi, any chance that you can provide the sponza scene asset?
> I try one copy from another repo yet it seems does not working, the program crashed when draw gbuffer.

Hi @horusli , a working build with the assets has been uploaded. Please check the releases section. Sorry about the delay, I've been a bit busy.

**Comment by horusli** [comment]
> > > Sure thing, I'll add a prebuilt release with the assets soon.
> > 
> > 
> > hi, any chance that you can provide the sponza scene asset?
> > I try one copy from another repo yet it seems does not working, the program crashed when draw gbuffer.
> 
> Hi @horusli , a working build with the assets has been uploaded. Please check the releases section. Sorry about the delay, I've been a bit busy.

thanks a lot!
