### ISSUE TITLE
Failed to configure on MSYS2 UCRT64

### ISSUE THREAD

**Issue by ghost** [diharaw/HybridRendering#13]
Please re-check your `CMakeLists.txt`. The configuration is done and the ninja build script is generated but there are errors on the ninja build script:

```
CMake Error:
  Running

   'C:/msys64/ucrt64/bin/ninja.exe' '-C' 'C:/msys64/home/Administrator/hybrid-rendering/build' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:3122: bad $-escape (literal $ must be written as $$)





CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Update: if I use "MSYS Makefiles" or "MinGW Makefiles" generator then it could generate the build script without any errors!

**Comment by diharaw** [comment]
Hi, only Visual Studio 2022 is tested at the moment. I have no plans to support anything else at the moment. Please feel free to submit an MR if you fix the issue.
