### ISSUE TITLE
Missing texture files

### ISSUE THREAD

**Issue by tommychouyc** [diharaw/HybridRendering#2]
When running the renderer, it is missing PNGs in the texture folder. Could you kindly provide the texture files or point to where to get them?

texture/LDR_RGBA_0.png
texture/LDR_RGBA_1.png
texture/blue_noise/sobol_256_4d.png
texture/blue_noise/scrambling_ranking_128x128_2d_1spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_2spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_4spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_8spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_16spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_32spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_64spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_128spp.png
texture/blue_noise/scrambling_ranking_128x128_2d_256spp.png

Thank you very much!

**Comment by tommychouyc** [comment]
bump

**Comment by diharaw** [comment]
Hey! Sorry about the delay. This project is undergoing a full overhaul right now and is a bit broken at the moment, I didn’t officially release it yet.

**Comment by tommychouyc** [comment]
Hi, thanks for the update. Looking forward to the finished version! Would it still be possible if you could provide access to the noise images? I would like to check out the feature implementations in the previous commits. 

Thanks!
