### ISSUE TITLE
Runtime error at launch

### ISSUE THREAD

**Issue by michaelmigliore** [diharaw/HybridRendering#6]
Hi, and thanks for sharing your work!  
The compilation went well but I have this runtime issue at launch:

![image](https://user-images.githubusercontent.com/73815580/137072744-63a67ae5-3d79-4704-9cf9-ba98af1fc392.png)

I have the exact same error when I run the built version in your release package.  
Do you have any idea?

I have built the application using default CMake options.  
- Windows 10 20H2
- RTX 2070
- Vulkan SDK 1.2.189.2

**Comment by diharaw** [comment]
Which driver version are you running? I recommend using the latest drivers. If not, try the debug build and see if that gives you anything more.

**Comment by michaelmigliore** [comment]
I'm running 442.80  
I have the same problem in Debug mode.

**Comment by diharaw** [comment]
I'm running 471.96 so it's almost definitely due to older drivers. Please install the latest ones available and try again.

**Comment by michaelmigliore** [comment]
You were right, updating the driver fix this issue, thanks!
