### ISSUE TITLE
Failed to find a suitable GPU (GeForce GTX 1060 6GB)

### ISSUE THREAD

**Issue by SamuelTallet** [diharaw/HybridRendering#8]
Hello,

When I run HybridRendering.exe (v1.0.0), I get this fatal error:

```
(Vulkan) Failed to find a suitable GPU. , FILE : vk.cpp , LINE : 3442
```

Here are some system informations:

OS : Windows 10.0.19043 Build 19043
GPU : NVIDIA GeForce GTX 1060 6GB
I have also an integrated Intel GPU...

GeForce Game Ready Driver 511.23

**Comment by diharaw** [comment]
Hi!

It seems like your GPU doesn’t support all the required extensions. This needs RTX 2000 series or AMD RX 6000 series GPU as a minimum unfortunately.

**Comment by SamuelTallet** [comment]
What are the required extensions?
- VK_KHR_ray_tracing_pipeline
- VK_KHR_acceleration_structure
- VK_EXT_descriptor_indexing

**Comment by diharaw** [comment]
It also uses VK_KHR_ray_query which your GPU doesn’t seem to support.

**Comment by SamuelTallet** [comment]
Indeed

```shell
vulkaninfo | grep VK_KHR_ray_tracing_pipeline
```

returns this

```shell
VK_KHR_ray_tracing_pipeline : extension revision 1
```

but

```shell
vulkaninfo | grep VK_KHR_ray_query
```

returns nothing 😕

I suggest to add `VK_KHR_ray_query` requirement in *README.md*

Anyway, thanks for your quick support! 😊

**Comment by diharaw** [comment]
Sorry, about that! Ray queries were added later on during the project and forgot to update the readme.

**Comment by SamuelTallet** [comment]
No problem!
